### ISSUE TITLE
Renaming to "ga4gh-metadata-schemas"

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-metadata/ga4gh-metadata#2]
More consistency through 

* ga4gh-metadata-schemas
* ga4gh-metadata-examples

... or dropping all prefixes.

Opinions, please?

**Comment by mcourtot** [comment]
+1 for consistency.

what about metadata-schemas, metadata-examples? That would allow for other types of repos than metadata while not repeating the ga4gh unnecessarily.

**Comment by mbaudis** [comment]
Yes, can do it like that (enforces the "metadata" part). Should rename now or never, though (before too many links get broken ...).

**Comment by mcourtot** [comment]
I was trying to find how to rename and reloading the page just worked ;) Thanks!
